apiVersion: v1
kind: Service
metadata:
  name: {{ include "controller.fullname" . }}{{ .Values.metrics.service.nameSuffix }}
  labels: {{- include "controller.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector: {{- include "controller.selectorLabels" . | nindent 4 }}
  ports:
    - name: {{ .Values.global.ports.httpPrefix }}{{ .Values.metrics.config.portName }}
      protocol: TCP
      port: 80
      targetPort: {{ .Values.metrics.config.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "controller.fullname" . }}-health
  labels: {{- include "controller.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector: {{- include "controller.selectorLabels" . | nindent 4 }}
  ports:
    - name:  {{ .Values.global.ports.httpPrefix }}{{ .Values.global.istio.proxy.portName }}
      protocol: TCP
      port: {{ .Values.global.istio.proxy.statusPort }}
      targetPort: {{ .Values.global.istio.proxy.statusPort }}
